name: Sync Assigned Issue to Private Repo

on:
  issues:
    types: [assigned]

jobs:
  extract_issue:
    name: Extract Issue Info
    runs-on: ubuntu-latest
    outputs:
      title: ${{ steps.extract.outputs.title }}
      body: ${{ steps.extract.outputs.body }}
      labels: ${{ steps.extract.outputs.labels }}
      assignee: ${{ steps.extract.outputs.assignee }}
      number: ${{ steps.extract.outputs.number }}
      url: ${{ steps.extract.outputs.url }}
    steps:
      - name: Extract info from issue
        id: extract
        run: |
          echo "title=${{ github.event.issue.title }}" >> $GITHUB_OUTPUT
          echo "body=${{ github.event.issue.body }}" >> $GITHUB_OUTPUT
          echo "labels=$(jq -c '[.[] | .name]' <<< '${{ toJson(github.event.issue.labels) }}')" >> $GITHUB_OUTPUT
          echo "assignee=${{ github.event.assignee.login }}" >> $GITHUB_OUTPUT
          echo "number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          echo "url=${{ github.event.issue.html_url }}" >> $GITHUB_OUTPUT

  create_in_private:
    name: Create Issue in Private Repo
    needs: extract_issue
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.create.outputs.issue-number }}
      html-url: ${{ steps.create.outputs.html-url }}
    steps:
      - name: Create issue in private repo
        id: create
        uses: peter-evans/create-issue@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: Manastik-Tech/dementia-app-v2
          title: ${{ needs.extract_issue.outputs.title }}
          body: ${{ needs.extract_issue.outputs.body }}
          labels: ${{ needs.extract_issue.outputs.labels }}
          assignees: ${{ needs.extract_issue.outputs.assignee }}

  comment_and_close:
    name: Comment, Label, and Close Original
    needs: [extract_issue, create_in_private]
    runs-on: ubuntu-latest
    steps:
      - name: Comment on original issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ needs.extract_issue.outputs.number }}
          body: |
            Assigned to ${{ needs.extract_issue.outputs.assignee }} - [Issue #${{ needs.create_in_private.outputs.issue-number }}](${{ needs.create_in_private.outputs.html-url }})

      - name: Add "assigned" label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          labels: assigned
          issue_number: ${{ needs.extract_issue.outputs.number }}

      - name: Close original issue
        uses: peter-evans/close-issue@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ needs.extract_issue.outputs.number }}
