name: Sync Assigned Issue to Private Repo

on:
  issues:
    types: [assigned]

jobs:
  # Create the issue in the private repository
  create-private-issue:
    runs-on: ubuntu-latest
    outputs:
      new_issue_number: ${{ steps.create-issue.outputs.issue-number }}
      new_issue_url: ${{ steps.create-issue.outputs.issue-html-url }}
    
    steps:
      - name: Create issue body file
        run: |
          echo "${{ github.event.issue.body }}" > /tmp/issue-body.md
          echo "" >> /tmp/issue-body.md
          echo "_Copied from [Manastik-Tech/Manastik-Teleneurorehab#${{ github.event.issue.number }}](https://github.com/Manastik-Tech/Manastik-Teleneurorehab/issues/${{ github.event.issue.number }})_" >> /tmp/issue-body.md
      
      - name: Create issue in private repo
        id: create-issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: Manastik-Tech/dementia-app-v2
          title: ${{ github.event.issue.title }}
          content-filepath: /tmp/issue-body.md
          labels: ${{ join(github.event.issue.labels.*.name, ',') }}
          assignees: ${{ github.event.issue.assignee.login }}

  # Update and close the original issue
  update-original-issue:
    runs-on: ubuntu-latest
    needs: create-private-issue
    
    steps:
      - name: Comment on original issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: "Assigned to ${{ github.event.issue.assignee.login }} - [Issue #${{ needs.create-private-issue.outputs.new_issue_number }}](${{ needs.create-private-issue.outputs.new_issue_url }})"
      
      - name: Add label to original issue
        uses: andymckay/labeler@master
        with:
          add-labels: "assigned"
          repo-token: ${{ secrets.GH_TOKEN }}
      
      - name: Close original issue
        uses: peter-evans/close-issue@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          comment: false
