name: Sync Assigned Issue to Private Repo
on:
  issues:
    types: [assigned]
jobs:
  # Create the issue in the private repository
  create-private-issue:
    runs-on: ubuntu-latest
    outputs:
      new_issue_number: ${{ fromJson(steps.create-issue.outputs.data).number }}
      new_issue_url: ${{ fromJson(steps.create-issue.outputs.data).html_url }}
    
    steps:
      - name: Get issue details
        id: get-issue
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/issues/{issue_number}
          owner: Manastik-Tech
          repo: Manastik-Teleneurorehab
          issue_number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Extract label names
        id: extract-labels
        run: |
          LABELS=$(echo '${{ steps.get-issue.outputs.data }}' | jq -c '[.labels[].name]')
          echo "ISSUE_LABELS=$LABELS" >> $GITHUB_OUTPUT
          
          ASSIGNEE=$(echo '${{ steps.get-issue.outputs.data }}' | jq -r '.assignee.login')
          echo "ASSIGNEE_LOGIN=$ASSIGNEE" >> $GITHUB_OUTPUT
      
      - name: Create issue in private repo
        id: create-issue
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/issues
          owner: Manastik-Tech
          repo: dementia-app-v2
          title: ${{ fromJson(steps.get-issue.outputs.data).title }}
          body: ${{ toJSON(fromJson(steps.get-issue.outputs.data).body) }}${{ '\n\n_Copied from [Manastik-Tech/Manastik-Teleneurorehab#' }}${{ github.event.issue.number }}${{ '](https://github.com/Manastik-Tech/Manastik-Teleneurorehab/issues/' }}${{ github.event.issue.number }}${{ ')_' }}
          labels: ${{ steps.extract-labels.outputs.ISSUE_LABELS }}
          assignees: '["${{ steps.extract-labels.outputs.ASSIGNEE_LOGIN }}"]'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  # Update and close the original issue
  update-original-issue:
    runs-on: ubuntu-latest
    needs: create-private-issue
    
    steps:
      - name: Comment on original issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: "Assigned to ${{ github.event.issue.assignee.login }} - [Issue #${{ needs.create-private-issue.outputs.new_issue_number }}](${{ needs.create-private-issue.outputs.new_issue_url }})"
      
      - name: Add label to original issue
        uses: andymckay/labeler@master
        with:
          add-labels: "assigned"
          repo-token: ${{ secrets.GH_TOKEN }}
      
      - name: Close original issue
        uses: peter-evans/close-issue@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          comment: false
